//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFPO {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class SystemSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SystemSettings defaultInstance = ((SystemSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SystemSettings())));
        
        public static SystemSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string USERNAME {
            get {
                return ((string)(this["USERNAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+UIt7ZQRqZvMYMeCzUT1MWhEgf8TA2DLdPPoMPws0yo=")]
        public string PASSWORD {
            get {
                return ((string)(this["PASSWORD"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STORE1")]
        public string STOREID {
            get {
                return ((string)(this["STOREID"]));
            }
            set {
                this["STOREID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.beautyeducationdirectory.com/api/index.php")]
        public string XMLRPCAPIURL {
            get {
                return ((string)(this["XMLRPCAPIURL"]));
            }
            set {
                this["XMLRPCAPIURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WkVNVUIwWFdBOVAzRkxQQ1kyMERTVE9SRTE=")]
        public string STORESECURITYKEY {
            get {
                return ((string)(this["STORESECURITYKEY"]));
            }
            set {
                this["STORESECURITYKEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PRINTERNAME {
            get {
                return ((string)(this["PRINTERNAME"]));
            }
            set {
                this["PRINTERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string PRINTNOCOPIES {
            get {
                return ((string)(this["PRINTNOCOPIES"]));
            }
            set {
                this["PRINTNOCOPIES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string DOWNLOADINTERVAL {
            get {
                return ((string)(this["DOWNLOADINTERVAL"]));
            }
            set {
                this["DOWNLOADINTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string CONFIGURED {
            get {
                return ((string)(this["CONFIGURED"]));
            }
            set {
                this["CONFIGURED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string PRINTTEMPLATE {
            get {
                return ((string)(this["PRINTTEMPLATE"]));
            }
            set {
                this["PRINTTEMPLATE"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WkVNVUIwWFdBOVAzRkxQQ1kyMERTVE9SRTE=")]
        public string DECRYPTKEY {
            get {
                return ((string)(this["DECRYPTKEY"]));
            }
        }
    }
}
